# Generated by Django 5.2.7 on 2025-11-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "ano_publicacao",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("capa_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
