# Generated by Django 5.2.7 on 2025-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0002_rename_capa_url_livro_capa_livro_identificador_api_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="identificador_api",
            field=models.CharField(default="N/A", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
