# Generated by Django 5.2.8 on 2025-11-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['-criado_em']},
        ),
    ]
