# Generated by Django 5.2.7 on 2025-11-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grupo", "0003_alter_topico_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topico",
            options={"ordering": ["criado_em"]},
        ),
    ]
