# Generated by Django 5.2.7 on 2025-11-23 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grupo", "0004_alter_topico_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="lidos_por",
            field=models.ManyToManyField(
                blank=True, related_name="mensagens_lidas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
