# Generated by Django 5.2.4 on 2025-11-21 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('alvo_tipo', models.CharField(blank=True, max_length=100)),
                ('alvo_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'Nova'), ('in_progress', 'Em andamento'), ('resolved', 'Resolvida'), ('rejected', 'Rejeitada')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-created_at'],
            },
        ),
    ]
